receivers:
  otlp:
    protocols:
      grpc:
        endpoint: https://otlp.nr-data.net:4317
      http:
        endpoint: https://otlp.nr-data.net:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug